export const data =[{
    "id":"1",
    "name":"More & More Unisex-Adult Cotton Hooded Neck Printed Hoodie",
    "image":"https://m.media-amazon.com/images/I/51UUPx3H1yL._UX569_.jpg",
    "category":"hoodies",
    "size":"medium",
    "price":"699",
    "color":"Black",
    "stock":"20",
},
{
    "id":"2",
    "name":"More & More Unisex-Adult Cotton Hooded Neck Avenger Printed Hoodie",
    "image":"https://m.media-amazon.com/images/I/81wh0qDcinL._UX679_.jpg",
    "category":"hoodies",
    "size":"large",
    "price":"599",
    "color":"Sky Blue",
    "stock":"0",
},
{
    "id":"3",
    "name":"More & More Unisex-Adult Cotton Hooded Neck Printed Hoodie",
    "image":"https://m.media-amazon.com/images/I/71oFZCAV7vL._UY741_.jpg",
    "category":"hoodies",
    "size":"medium",
    "price":"699",
    "color":"Brown",
    "stock":"20",
},
{
    "id":"4",
    "name":"More & More Unisex-Adult Cotton Hooded Neck La Casa Printed Hoodie",
    "image":"https://m.media-amazon.com/images/I/71r3iIT8HQL._UY741_.jpg",
    "category":"hoodies",
    "size":"small",
    "price":"699",
    "color":"Red",
    "stock":"20",
},
{
    "id":"5",
    "name":"Van Heusen Men's Regular Fit Polo Shirt",
    "image":"https://m.media-amazon.com/images/I/818niea1luL._UX569_.jpg",
    "category":"tshirt",
    "size":"medium",
    "price":"299",
    "color":"White",
    "stock":"20",
},
{
    "id":"6",
    "name":"Van Heusen Athleisure Men's Regular Fit Polo",
    "image":"https://m.media-amazon.com/images/I/3133xMD3MuL.jpg",
    "category":"tshirt",
    "size":"large",
    "price":"299",
    "color":"Black",
    "stock":"20",
},
{
    "id":"7",
    "name":"AMERICAN CREW Polo T-Shirts for Men",
    "image":"https://m.media-amazon.com/images/I/710AFAbxjYL._UY741_.jpg",
    "category":"tshirt",
    "size":"medium",
    "price":"369",
    "color":"Grey",
    "stock":"0",
},
{
    "id":"8",
    "name":"Amazon Brand - Inkast Denim Co. Men's Slim Stretchable Jeans",
    "image":"https://m.media-amazon.com/images/I/91ct3xEn5pL._UY879_.jpg",
    "category":"jeans",
    "size":"medium",
    "price":"899",
    "color":"Blue",
    "stock":"20",
},
{
    "id":"9",
    "name":"Urbano Fashion Men's Slim Fit Black Stretch Jeans",
    "image":"https://m.media-amazon.com/images/I/611hFiiUv4L._UX679_.jpg",
    "category":"jeans",
    "size":"large",
    "price":"899",
    "color":"Black",
    "stock":"20",
},
{
    "id":"10",
    "name":"Veirdo Official Disney Printed Oversized T Shirts for Men, Half Sleeves Baggy Tshirt for Men, Cotton Loose Fit T Shirts for Men & Boys, Drop Shoulder Tshirt for Men",
    "image":"https://m.media-amazon.com/images/I/61CGqRScDaL._UL1500_.jpg",
    "category":"tshirt",
    "size":"small",
    "price":"299",
    "color":"White",
    "stock":"20",
},
{
    "id":"11",
    "name":"LEOTUDE Oversized Mens Cotton Blend Half Sleeve T-Shirts",
    "image":"https://m.media-amazon.com/images/I/71As8HASloL._UY741_.jpg",
    "category":"tshirt",
    "size":"medium",
    "price":"499",
    "color":"Yellow",
    "stock":"20",
},
{
    "id":"12",
    "name":"ABSOLUTE DEFENSE Hoodies for Men Women Casual Stylish Latest Sweatshirt Winter Jacket Boy Girl",
    "image":"https://m.media-amazon.com/images/I/614a0HEK8jL._UL1500_.jpg",
    "category":"hoodies",
    "size":"large",
    "price":"699",
    "color":"Purple",
    "stock":"20",
}]